version: '3.7'

services:
  xmrig:
    build:
      context: .
      dockerfile: Dockerfile
    image: blackplane/xmrig
    deploy:
      resources:
        limits:
          cpus: "1.00"
    restart: always
    container_name: "xmrig-container"
    environment:
      XMRIG_JSON_CONFIG_PATH: "/app/etc/config.json"
    volumes:
      - ${PWD}:/app/etc

